### ISSUE TITLE
searchEncode returns NA rows

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/ENCODExplorer#2]
```
> searchEncode("MNase+GM12878")[1:4]
[1] "results : 2 entries"
    accession assay_term_name dataset_type                      lab
1 ENCSR000CXP       MNase-seq   experiment Michael Snyder, Stanford
2        <NA>            <NA>         <NA>                     <NA>
```
If we do the [same search](https://www.encodeproject.org/search/?searchTerm=MNase%2BGM12878) in the encode project web portal, we see that the search returns an `experiment` and a `publication` data type. The latter is probably what is causing this bug.

**Comment by louisgendron26** [comment]
Les résultats sont similaires entre la recherche sur le portail de Encode et le resultat de l'appel de fonction searchEncode("MNase+GM12878").
Possibilité que le problème proviennait de chez Encode et qu'il a été fixé entre temps.
