### ISSUE TITLE
downloadEncode with force == FALSE

### ISSUE THREAD

**Issue by kapka2** [CharlesJB/ENCODExplorer#38]
I am trying to call downloadEncode with force == FALSE.  In download_single_file, md5sum is called on dir/fileName, but fileName had already been concatenated with dir a couple of lines above.  Therefore, the md5sum_file cannot be compared with md5sum_encode and an error is given.

**Comment by CharlesJB** [comment]
Thanks for reporting this bug! I'll try to push a patch on the release branch of Bioconductor today.

**Comment by CharlesJB** [comment]
It's pushed, it should be available after the nightly build. Check for version 2.2.1 on Bioconductor.
