### ISSUE TITLE
downloadEncode error

### ISSUE THREAD

**Issue by r-lehtonen** [CharlesJB/ENCODExplorer#39]
I was testing the ENCODExplorer package, but the function downloadEncode give a error:

> downloadEncode(query_results, df=encode_df, format = "bed")
Error in download.file(url = paste0(encode_root, href), quiet = TRUE,  : 
  'curl' call had nonzero exit status
In addition: Warning message:
running command 'curl -L -s -S "https://www.encodeproject.org/files/ENCFF001VCK/@@download/ENCFF001VCK.bed.gz"  -o "./ENCFF001VCK.bed.gz"' had status 127

**Comment by ericfournier2** [comment]
Duplicate with issue #48
