### ISSUE TITLE
Database is not completed?

### ISSUE THREAD

**Issue by hgu0717** [CharlesJB/ENCODExplorer#43]
Hey, 

I was looking for RNA-seq data for one cell lines, however, it returns nothing with query function.

`> query_results <- queryEncode(df=encode_df, organism = "Homo sapiens", biosample_name="GM12878",assay="RNA-seq", fixed=FALSE)
> head(query_results)
Empty data.table (0 rows) of 73 cols: accession,file_accession,file_type,file_format,file_size,output_category...` 

This is not consistent with searching results in ENCODE portal. 
[https://www.encodeproject.org/search/?type=Experiment&status=released&biosample_ontology.classification=cell+line&assay_title=polyA+RNA-seq&biosample_ontology.term_name=GM12878&assay_title=polyA+RNA-seq&biosample_ontology.classification=cell+line](url)

**Comment by ericfournier2** [comment]
Hello hgu0717,

there was indeed an issue publishing the most up to date version of the database to Bioconductor. I am currently compiling an up to date version, and will share it with you as soon as it is completed.

Cheers,
-Eric

**Comment by ericfournier2** [comment]
Sorry for not getting back to you, we ended up making some major changes to the way ENCODExplorer is structured due to size limit issues with Bioconductor. ENCODExplorer has now been updated with the most recent available data at the time of BioConductor release 3.9.
