### ISSUE TITLE
missing function queryConsensusPeaks in Bioc v.2.10.0

### ISSUE THREAD

**Issue by gaiatek** [CharlesJB/ENCODExplorer#51]
Hi, 

I am trying to follow the bioconductor vignette for ENCODEExplorer and when I try to obtain consensus Peaks from ChIP-Seq  (section 5.1) I get the following error: 
```r 
res = queryConsensusPeaks("22Rv1", "GRCh38", "CTCF")
Error in queryConsensusPeaks("22Rv1", "GRCh38", "CTCF"): 
  could not find function "queryConsensusPeaks"
```
It looks like the function is not part of the package anymore? I also looked into package ENCODExplorerData, but to no avail... Could you point me to the function? thanks!

session info: 
- Session info --------------------------------------------------
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-02-16                  

- Packages ------------------------------------------------------
 package                * version  date       lib source        
 AnnotationDbi          * 1.46.1   2019-08-20 [1] Bioconductor  
 AnnotationFilter       * 1.8.0    2019-05-02 [1] Bioconductor  
 AnnotationHub          * 2.16.1   2019-09-04 [1] Bioconductor  
 assertthat               0.2.1    2019-03-21 [1] CRAN (R 3.6.1)
 backports                1.1.5    2019-10-02 [1] CRAN (R 3.6.1)
 Biobase                * 2.44.0   2019-05-02 [1] Bioconductor  
 BiocFileCache          * 1.8.0    2019-05-02 [1] Bioconductor  
 BiocGenerics           * 0.30.0   2019-05-02 [1] Bioconductor  
 BiocManager              1.30.10  2019-11-16 [1] CRAN (R 3.6.1)
 BiocParallel             1.18.1   2019-08-06 [1] Bioconductor  
 biomaRt                  2.40.5   2019-10-01 [1] Bioconductor  
 Biostrings               2.52.0   2019-05-02 [1] Bioconductor  
 bit                      1.1-15.1 2020-01-14 [1] CRAN (R 3.6.2)
 bit64                    0.9-7    2017-05-08 [1] CRAN (R 3.6.0)
 bitops                   1.0-6    2013-08-17 [1] CRAN (R 3.6.0)
 blob                     1.2.1    2020-01-20 [1] CRAN (R 3.6.2)
 boot                     1.3-24   2019-12-20 [2] CRAN (R 3.6.2)
 broom                    0.5.4    2020-01-27 [1] CRAN (R 3.6.2)
 callr                    3.4.2    2020-02-12 [1] CRAN (R 3.6.2)
 caTools                  1.18.0   2020-01-17 [1] CRAN (R 3.6.2)
 cellranger               1.1.0    2016-07-27 [1] CRAN (R 3.6.1)
 checkmate                2.0.0    2020-02-06 [1] CRAN (R 3.6.2)
 cli                      2.0.1    2020-01-08 [1] CRAN (R 3.6.2)
 codetools                0.2-16   2018-12-24 [2] CRAN (R 3.6.2)
 colorRamps               2.3      2012-10-29 [1] CRAN (R 3.6.0)
 colorspace               1.4-1    2019-03-18 [1] CRAN (R 3.6.1)
 crayon                   1.3.4    2017-09-16 [1] CRAN (R 3.6.1)
 curl                     4.3      2019-12-02 [1] CRAN (R 3.6.1)
 data.table               1.12.8   2019-12-09 [1] CRAN (R 3.6.2)
 DBI                      1.1.0    2019-12-15 [1] CRAN (R 3.6.2)
 dbplyr                 * 1.4.2    2019-06-17 [1] CRAN (R 3.6.1)
 DelayedArray             0.10.0   2019-05-02 [1] Bioconductor  
 desc                     1.2.0    2018-05-01 [1] CRAN (R 3.6.1)
 devtools                 2.2.1    2019-09-24 [1] CRAN (R 3.6.1)
 digest                   0.6.23   2019-11-23 [1] CRAN (R 3.6.1)
 doParallel               1.0.15   2019-08-02 [1] CRAN (R 3.6.1)
 dplyr                  * 0.8.4    2020-01-31 [1] CRAN (R 3.6.2)
 DT                     * 0.12     2020-02-05 [1] CRAN (R 3.6.2)
 edgeR                  * 3.26.8   2019-09-01 [1] Bioconductor  
 ellipsis                 0.3.0    2019-09-20 [1] CRAN (R 3.6.1)
 ENCODExplorer          * 2.10.0   2019-05-02 [1] Bioconductor  
 ENCODExplorerData      * 0.99.1   2020-02-16 [1] Bioconductor  
 ensembldb              * 2.8.1    2019-10-11 [1] Bioconductor  
 fansi                    0.4.1    2020-01-08 [1] CRAN (R 3.6.2)
 fastmap                  1.0.1    2019-10-08 [1] CRAN (R 3.6.1)
 forcats                * 0.4.0    2019-02-17 [1] CRAN (R 3.6.1)
 foreach                * 1.4.8    2020-02-09 [1] CRAN (R 3.6.2)
 fs                       1.3.1    2019-05-06 [1] CRAN (R 3.6.1)
 gdata                    2.18.0   2017-06-06 [1] CRAN (R 3.6.0)
 generics                 0.0.2    2018-11-29 [1] CRAN (R 3.6.1)
 GenomeInfoDb           * 1.20.0   2019-05-02 [1] Bioconductor  
 GenomeInfoDbData         1.2.1    2019-11-30 [1] Bioconductor  
 GenomicAlignments        1.20.1   2019-06-18 [1] Bioconductor  
 GenomicFeatures        * 1.36.4   2019-07-11 [1] Bioconductor  
 GenomicRanges          * 1.36.1   2019-09-06 [1] Bioconductor  
 ggplot2                * 3.2.1    2019-08-10 [1] CRAN (R 3.6.1)
 glue                     1.3.1    2019-03-12 [1] CRAN (R 3.6.1)
 gplots                   3.0.1.2  2020-01-11 [1] CRAN (R 3.6.2)
 graph                    1.62.0   2019-05-02 [1] Bioconductor  
 graphite               * 1.30.0   2019-05-02 [1] Bioconductor  
 gtable                   0.3.0    2019-03-25 [1] CRAN (R 3.6.1)
 gtools                   3.8.1    2018-06-26 [1] CRAN (R 3.6.0)
 haven                    2.2.0    2019-11-08 [1] CRAN (R 3.6.1)
 hms                      0.5.3    2020-01-08 [1] CRAN (R 3.6.2)
 htmltools                0.4.0    2019-10-04 [1] CRAN (R 3.6.1)
 htmlwidgets              1.5.1    2019-10-08 [1] CRAN (R 3.6.1)
 httpuv                   1.5.2    2019-09-11 [1] CRAN (R 3.6.1)
 httr                     1.4.1    2019-08-05 [1] CRAN (R 3.6.1)
 interactiveDisplayBase   1.22.0   2019-05-02 [1] Bioconductor  
 IRanges                * 2.18.3   2019-09-24 [1] Bioconductor  
 iterators                1.0.12   2019-07-26 [1] CRAN (R 3.6.1)
 jsonlite                 1.6.1    2020-02-02 [1] CRAN (R 3.6.2)
 KernSmooth               2.23-16  2019-10-15 [2] CRAN (R 3.6.2)
 later                    1.0.0    2019-10-04 [1] CRAN (R 3.6.1)
 lattice                  0.20-38  2018-11-04 [2] CRAN (R 3.6.2)
 lazyeval                 0.2.2    2019-03-15 [1] CRAN (R 3.6.1)
 lifecycle                0.1.0    2019-08-01 [1] CRAN (R 3.6.1)
 limma                  * 3.40.6   2019-07-26 [1] Bioconductor  
 lme4                     1.1-21   2019-03-05 [1] CRAN (R 3.6.1)
 locfit                   1.5-9.1  2013-04-20 [1] CRAN (R 3.6.1)
 lubridate                1.7.4    2018-04-11 [1] CRAN (R 3.6.1)
 magrittr                 1.5      2014-11-22 [1] CRAN (R 3.6.1)
 MASS                     7.3-51.5 2019-12-20 [2] CRAN (R 3.6.2)
 Matrix                   1.2-18   2019-11-27 [1] CRAN (R 3.6.1)
 matrixStats              0.55.0   2019-09-07 [1] CRAN (R 3.6.1)
 memoise                  1.1.0    2017-04-21 [1] CRAN (R 3.6.1)
 mime                     0.9      2020-02-04 [1] CRAN (R 3.6.2)
 minqa                    1.2.4    2014-10-09 [1] CRAN (R 3.6.1)
 modelr                   0.1.5    2019-08-08 [1] CRAN (R 3.6.1)
 munsell                  0.5.0    2018-06-12 [1] CRAN (R 3.6.1)
 nlme                     3.1-144  2020-02-06 [1] CRAN (R 3.6.2)
 nloptr                   1.2.1    2018-10-03 [1] CRAN (R 3.6.1)
 packrat                  0.5.0    2018-11-14 [1] CRAN (R 3.6.1)
 pbkrtest                 0.4-7    2017-03-15 [1] CRAN (R 3.6.1)
 pillar                   1.4.3    2019-12-20 [1] CRAN (R 3.6.2)
 pkgbuild                 1.0.6    2019-10-09 [1] CRAN (R 3.6.1)
 pkgconfig                2.0.3    2019-09-22 [1] CRAN (R 3.6.1)
 pkgload                  1.0.2    2018-10-29 [1] CRAN (R 3.6.1)
 plyr                     1.8.5    2019-12-10 [1] CRAN (R 3.6.2)
 prettyunits              1.1.1    2020-01-24 [1] CRAN (R 3.6.2)
 processx                 3.4.2    2020-02-09 [1] CRAN (R 3.6.2)
 progress                 1.2.2    2019-05-16 [1] CRAN (R 3.6.1)
 promises                 1.1.0    2019-10-04 [1] CRAN (R 3.6.1)
 ProtGenerics             1.16.0   2019-05-02 [1] Bioconductor  
 ps                       1.3.0    2018-12-21 [1] CRAN (R 3.6.2)
 purrr                  * 0.3.3    2019-10-18 [1] CRAN (R 3.6.1)
 R6                       2.4.1    2019-11-12 [1] CRAN (R 3.6.1)
 rappdirs                 0.3.1    2016-03-28 [1] CRAN (R 3.6.1)
 Rcpp                     1.0.3    2019-11-08 [1] CRAN (R 3.6.1)
 RCurl                    1.98-1.1 2020-01-19 [1] CRAN (R 3.6.2)
 readr                  * 1.3.1    2018-12-21 [1] CRAN (R 3.6.1)
 readxl                   1.3.1    2019-03-13 [1] CRAN (R 3.6.1)
 remotes                  2.1.1    2020-02-15 [1] CRAN (R 3.6.2)
 reprex                   0.3.0    2019-05-16 [1] CRAN (R 3.6.1)
 reshape2                 1.4.3    2017-12-11 [1] CRAN (R 3.6.1)
 rlang                    0.4.4    2020-01-28 [1] CRAN (R 3.6.2)
 rprojroot                1.3-2    2018-01-03 [1] CRAN (R 3.6.1)
 Rsamtools                2.0.3    2019-10-10 [1] Bioconductor  
 RSQLite                  2.2.0    2020-01-07 [1] CRAN (R 3.6.2)
 rstudioapi               0.11     2020-02-07 [1] CRAN (R 3.6.2)
 rtracklayer              1.44.4   2019-09-06 [1] Bioconductor  
 rvest                    0.3.5    2019-11-08 [1] CRAN (R 3.6.1)
 S4Vectors              * 0.22.1   2019-09-09 [1] Bioconductor  
 scales                 * 1.1.0    2019-11-18 [1] CRAN (R 3.6.1)
 sessioninfo              1.1.1    2018-11-05 [1] CRAN (R 3.6.1)
 shiny                  * 1.4.0    2019-10-10 [1] CRAN (R 3.6.1)
 shinythemes            * 1.1.2    2018-11-06 [1] CRAN (R 3.6.1)
 stringi                  1.4.4    2020-01-09 [1] CRAN (R 3.6.2)
 stringr                * 1.4.0    2019-02-10 [1] CRAN (R 3.6.1)
 SummarizedExperiment     1.14.1   2019-07-31 [1] Bioconductor  
 testthat                 2.3.1    2019-12-01 [1] CRAN (R 3.6.1)
 tibble                 * 2.1.3    2019-06-06 [1] CRAN (R 3.6.1)
 tidyr                  * 1.0.2    2020-01-24 [1] CRAN (R 3.6.2)
 tidyselect               1.0.0    2020-01-27 [1] CRAN (R 3.6.2)
 tidyverse              * 1.3.0    2019-11-21 [1] CRAN (R 3.6.1)
 usethis                  1.5.1    2019-07-04 [1] CRAN (R 3.6.1)
 variancePartition      * 1.14.1   2019-10-01 [1] Bioconductor  
 vctrs                    0.2.2    2020-01-24 [1] CRAN (R 3.6.2)
 withr                    2.1.2    2018-03-15 [1] CRAN (R 3.6.1)
 XML                      3.99-0.3 2020-01-20 [1] CRAN (R 3.6.2)
 xml2                     1.2.2    2019-08-09 [1] CRAN (R 3.6.1)
 xtable                   1.8-4    2019-04-21 [1] CRAN (R 3.6.2)
 XVector                  0.24.0   2019-05-02 [1] Bioconductor  
 yaml                     2.2.1    2020-02-01 [1] CRAN (R 3.6.2)
 zlibbioc                 1.30.0   2019-05-02 [1] Bioconductor

**Comment by ericfournier2** [comment]
Hi,

I don't know about version ENCODExplorer version 2.10 (which probably was in BioConductor release 2.9), but the function is definitely in ENCODExplorer 2.12.1, the one in the current BioConductor release (Bioc 2.10). Is there a reason why you can't switch to that one?

Cheers,
-Eric

**Comment by gaiatek** [comment]
Thanks Eric!
Using version 2.12.1 has fixed the issue.
